# Generated by Django 5.1.5 on 2025-02-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_assist', '0003_remove_employee_id_employee_emp_id'),
    ]

    operations = [
    ]
