# Generated by Django 5.1.5 on 2025-02-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_assist', '0004_auto_20250210_1419'),
    ]

    operations = [
    ]
