# Generated by Django 5.1.5 on 2025-02-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_assist', '0006_remove_employee_emp_id_employee_id'),
    ]

    operations = [
    ]
