# Generated by Django 5.1.5 on 2025-02-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_assist', '0007_auto_20250210_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性')], default='男性', max_length=2),
        ),
    ]
