# Generated by Django 5.1.6 on 2025-02-14 01:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_assist', '0008_alter_employee_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
            ],
        ),
        migrations.CreateModel(
            name='AllowanceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_assist.allowance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_assist.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'allowance'), name='unique_employee_allowance')],
            },
        ),
    ]
