# Generated by Django 5.1.6 on 2025-02-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_assist', '0010_allowance_employee_allowance_paymonth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='allowance',
            name='paymonth',
        ),
    ]
