# Generated by Django 5.1.6 on 2025-02-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_assist', '0012_allowance_employee_allowance_paymonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
