# Generated by Django 5.1.6 on 2025-02-25 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_assist', '0017_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
