# Generated by Django 5.1.6 on 2025-02-25 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_assist', '0020_alter_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ManyToManyField(related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
