# Generated by Django 5.1.6 on 2025-02-25 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_assist', '0021_remove_employee_user_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
